const BASE_TYPE = 'app'

export enum BaseTypes {
    GET_INITAL_DATA = "GET_INITIAL_DATA",
    SET_INITAL_DATA = "SET_INITIAL_DATA",
    GET_ABOUT_ME_DATA = "GET_ABOUT_ME_DATA",
    SET_ABOUT_ME_DATA = "SET_ABOUT_ME_DATA"
}
